export const user_management_mockdata = [
  {
    account_no: "ACCT123456",
    first_name: "James",
    middle_name: "Robert",
    last_name: "Wilson",
    email: "james.wilson@email.com",
    contact_no: "+1-555-012-3456",
    address: "145 Oak Street, Springfield",
    role: "Admin",
    status: true,
  },
  {
    account_no: "ACCT234567",
    first_name: "Sarah",
    middle_name: "Elizabeth",
    last_name: "Taylor",
    email: "sarah.taylor@email.com",
    contact_no: "+1-555-012-3457",
    address: "234 Maple Avenue, Springfield",
    role: "Treasurer",
    status: false,
  },
  {
    account_no: "ACCT345678",
    first_name: "Michael",
    middle_name: "John",
    last_name: "Brown",
    email: "michael.brown@email.com",
    contact_no: "+1-555-012-3458",
    address: "456 Pine Road, Springfield",
    role: "Officer",
    status: false,
  },
  {
    account_no: "ACCT456789",
    first_name: "Lisa",
    middle_name: "Marie",
    last_name: "Davis",
    email: "lisa.davis@email.com",
    contact_no: "+1-555-012-3459",
    address: "567 Cedar Drive, Springfield",
    role: "Offender",
    status: true,
  },
  {
    account_no: "ACCT567890",
    first_name: "William",
    middle_name: "James",
    last_name: "Miller",
    email: "william.miller@email.com",
    contact_no: "+1-555-012-3460",
    address: "678 Cherry Lane, Springfield",
    role: "Admin",
    status: false,
  },
  {
    account_no: "ACCT678901",
    first_name: "Emma",
    middle_name: "Rose",
    last_name: "Wilson",
    email: "emma.wilson@email.com",
    contact_no: "+1-555-012-3461",
    address: "789 Walnut Street, Springfield",
    role: "Treasurer",
    status: false,
  },
  {
    account_no: "ACCT789012",
    first_name: "David",
    middle_name: "Lee",
    last_name: "Moore",
    email: "david.moore@email.com",
    contact_no: "+1-555-012-3462",
    address: "890 Oak Avenue, Springfield",
    role: "Officer",
    status: true,
  },
  {
    account_no: "ACCT890123",
    first_name: "Olivia",
    middle_name: "Grace",
    last_name: "Taylor",
    email: "olivia.taylor@email.com",
    contact_no: "+1-555-012-3463",
    address: "123 Maple Boulevard, Springfield",
    role: "Offender",
    status: true,
  },
  {
    account_no: "ACCT901234",
    first_name: "Joseph",
    middle_name: "Mark",
    last_name: "Brown",
    email: "joseph.brown@email.com",
    contact_no: "+1-555-012-3464",
    address: "456 Pine Street, Springfield",
    role: "Admin",
    status: false,
  },
  {
    account_no: "ACCT012345",
    first_name: "Ava",
    middle_name: "Joy",
    last_name: "Davis",
    email: "ava.davis@email.com",
    contact_no: "+1-555-012-3465",
    address: "567 Cedar Avenue, Springfield",
    role: "Treasurer",
    status: true,
  },
  {
    account_no: "ACCT123456",
    first_name: "Robert",
    middle_name: "William",
    last_name: "Miller",
    email: "robert.miller@email.com",
    contact_no: "+1-555-012-3466",
    address: "678 Cherry Street, Springfield",
    role: "Officer",
    status: false,
  },
  {
    account_no: "ACCT234567",
    first_name: "Isabella",
    middle_name: "Kate",
    last_name: "Wilson",
    email: "isabella.wilson@email.com",
    contact_no: "+1-555-012-3467",
    address: "789 Walnut Avenue, Springfield",
    role: "Offender",
    status: true,
  },
  {
    account_no: "ACCT345678",
    first_name: "Richard",
    middle_name: "Thomas",
    last_name: "Moore",
    email: "richard.moore@email.com",
    contact_no: "+1-555-012-3468",
    address: "890 Oak Boulevard, Springfield",
    role: "Admin",
    status: true,
  },
  {
    account_no: "ACCT456789",
    first_name: "Sophia",
    middle_name: "Patricia",
    last_name: "Taylor",
    email: "sophia.taylor@email.com",
    contact_no: "+1-555-012-3469",
    address: "123 Maple Street, Springfield",
    role: "Treasurer",
    status: true,
  },
  {
    account_no: "ACCT567890",
    first_name: "Charles",
    middle_name: "James",
    last_name: "Brown",
    email: "charles.brown@email.com",
    contact_no: "+1-555-012-3470",
    address: "456 Pine Boulevard, Springfield",
    role: "Officer",
    status: true,
  },
  {
    account_no: "ACCT678901",
    first_name: "Mia",
    middle_name: "Sarah",
    last_name: "Davis",
    email: "mia.davis@email.com",
    contact_no: "+1-555-012-3471",
    address: "567 Cedar Street, Springfield",
    role: "Offender",
    status: true,
  },
  {
    account_no: "ACCT789012",
    first_name: "Thomas",
    middle_name: "Robert",
    last_name: "Miller",
    email: "thomas.miller@email.com",
    contact_no: "+1-555-012-3472",
    address: "678 Cherry Avenue, Springfield",
    role: "Admin",
    status: true,
  },
  {
    account_no: "ACCT890123",
    first_name: "Charlotte",
    middle_name: "Lisa",
    last_name: "Wilson",
    email: "charlotte.wilson@email.com",
    contact_no: "+1-555-012-3473",
    address: "789 Walnut Boulevard, Springfield",
    role: "Treasurer",
    status: true,
  },
];